version: "3.9"

services:
  shorten-link:
    build: .
    container_name: shorten-link
    restart: always
    ports:
      - 3333:3333
    links: 
      - database
    depends_on:
      - database
    volumes:
      - .:/usr/src/app/
    env_file: .env
    environment:
      WAIT_HOSTS:  database:5432
    networks:
      - node-shorten-network
  database:
    image: postgres
    container_name: database-shorten-link
    restart: always
    ports:
      - 5432:5432
    environment:
      - POSTGRES_USER=docker
      - POSTGRES_PASSWORD=docker
      - POSTGRES_DB=shorten-link
    volumes:
      - ./docker_postgres_init.sql:/docker-entrypoint-initdb.d/docker_postgres_init.sql
    networks:
      - node-shorten-network
networks:
  node-shorten-network:
    driver: bridge