version: "3.9"

services:
  app:
    build: .
    container_name: shorten-link
    restart: always
    ports:
      - 3333:3333
    links: 
      - database
    depends_on:
      - database
    volumes:
      - .:/usr/src/app/
    env_file: .env
    networks:
      - node-shorten-network
  database:
    image: postgres
    container_name: database-shorten-link
    restart: always
    ports:
      - 5432:5432
    environment:
      - POSTGRES_USER=docker
      - POSTGRES_PASSWORD=docker
      - POSTGRES_DB=shorten-link
    volumes:
      - pgdata:/data/postgres
volumes:
  pgdata:
    driver: local
networks:
  node-shorten-network:
    driver: bridge