name: DEV - Run build and tests
on:
  push:
    branches:
      - dev
  pull_request:
    branches:
      - dev
  workflow_dispatch:
jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version:
          - 14.x
    steps:
      - uses: actions/checkout@v2
      - name: 'Use Node.js ${{ matrix.node-version }}'
        uses: actions/setup-node@v1
        with:
          node-version: '${{ matrix.node-version }}'
      - name: Install Packages
        run: yarn install
      - name: Build project
        run: yarn build
  test:
    runs-on: ubuntu-latest
    env:
      NODE_ENV: test
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Start docker containers
        run: |
          docker-compose up -d
          sleep 20  
          docker-compose exec shorten-link yarn 
          docker-compose logs shorten-link
          docker exec shorten-link yarn migration:run
          docker exec shorten-link yarn migration-test:run

      - name: Run backend unit and integration tests
        run: |
          docker exec shorten-link yarn test

      - if: always()
        uses: ouzi-dev/commit-status-updater@v1.1.0
        with:
          name: "Run tests"
          status: "${{ job.status }}"
